### ISSUE TITLE
TestNodeConnPoolIntegration doesn't pass after changing port from 19042 to 9042

### ISSUE THREAD

**Issue by Michal-Leszczynski** [mmatczuk/scylla-go-driver#147]
Connection pool lacks the mechanism to detect shard aware port from scylla supported.
For the first connection created in connection pool, we should take whatever port we are given at first, but the rest of connections should use shard aware port so that we can create connections on all shards.

**Comment by Neofine** [comment]
![Screenshot from 2022-03-08 20-13-55](https://user-images.githubusercontent.com/29147083/157308715-a7da777e-7b48-48e0-90cc-5181b9a9fe91.png)

This error appears.

**Comment by Neofine** [comment]
Update: Integration tests failed because of too little sleep time in the `TestNodeConnPoolIntegration`. It had little to do with shard awareness of the given port.
