### ISSUE TITLE
add Session

### ISSUE THREAD

**Issue by mmatczuk** [mmatczuk/scylla-go-driver#150]
Session needs to resolve DNS address of provided hosts and initialize whole driver.
I addition to that it manages queries and provides means for query execution.

**Comment by Choraden** [comment]
Could you explain little more what's up with resolving DNS addresses? As I look at Dial function examples (https://pkg.go.dev/net#Dial) I can see it is able to connect to given IP as well as to given domain name. @mmatczuk
