### ISSUE TITLE
fix reading error found by fuzzing

### ISSUE THREAD

**Issue by mmatczuk** [mmatczuk/scylla-go-driver#212]
Data added in 9eb030b7

**Comment by Michal-Leszczynski** [comment]
The problem occurs when we want to allocate a slice that is too big, so we should probably set some limit to it.
Unfortunately, the limit can be rather big:

> The maximum number of cells (rows x columns) in a single partition is 2 billion.

Source: https://cwiki.apache.org/confluence/display/CASSANDRA2/CassandraLimitations

With this limit, fuzzing tests still won't pass.
Can we set some more realistic and smaller limit? Or maybe we should make sure that this kind of tests are ignored?
