### ISSUE TITLE
TestCloseHangingIntegration bug

### ISSUE THREAD

**Issue by Michal-Leszczynski** [mmatczuk/scylla-go-driver#215]
Approximately 1/3 tries of running **TestCloseHangingIntegration** does not end at all. That's because program gets stuck in this for loop:
```go
func (c *Conn) sendController() {
	for {
		if size := c.Waiting(); size < targetWaiting {
			break
		}
		time.Sleep(50 * time.Millisecond)
	}
}
```
Where size = **max uint**
That's because `metrics.InQueue` decreases when it is equal to 0.
Interestingly enough, I cannot observe such behavior when I comment out this line in **TestCloseHangingIntegration**:
```go
h.exec("DROP KEYSPACE mykeyspace")
```

**Comment by Choraden** [comment]
That's because we decrement  inQueue while receiving closeRequest connWriter::loop(), which is fatal!
```go
r := <-c.requestCh
c.metrics.InQueue.Dec()
if r == _connCloseRequest {
    return
}
```
Let's decrement after checking closeRequest.

**Comment by Choraden** [comment]
Nevertheless, I don't see why such behavior is observed only when we drop keyspace. 
My guess is that executing extra query before closing connection gives enough time for all the other request to finish, so that inQueue is equal to 0 and it overflows while decrementing.
